server:
  port: 8090

spring:
  datasource:
    url: jdbc:sqlite:test.db
    driver-class-name: org.sqlite.JDBC
    username:
    password:
  redis:
    host: localhost
    port: 6379
    timeout: 6000ms

mybatis:
  mapper-locations: classpath:mapper/*.xml
mybatis-plus:
   configuration:
    jdbc-type-for-null: 'null'

